const HOUSES = [
  {
    id: "1528-ne-97th",
    color: "#4F86C6",
    nickname: "Maple Leaf",
    address: "1528 NE 97th St, Seattle, WA 98115",
    image: "images/1528-ne-97th.jpg",
    url: "https://www.compass.com/homedetails/1528-NE-97th-St-Seattle-WA-98115/1OX38Y_pid/",
    status: "Active",
    daysOnMarket: 3,
    price: 1091500,
    lastSoldPrice: 1250000,
    lastSoldYear: 2023,
    sqft: 2980,
    lotSqft: 5109,
    bedrooms: 4,
    bathrooms: 4,
    bathroomsFull: 2,
    bathroomsThreeQuarter: 1,
    bathroomsHalf: 1,
    yearBuilt: 1927,
    yearRenovated: 2004,
    stories: 2,
    basement: true,
    basementSqft: 990,
    parking: "2 uncovered",
    annualTax: 11588,
    hoaMonthly: 0,
    heating: "Forced air, high efficiency",
    cooling: "None",
    neighborhood: "Maple Leaf",
    features: [
      "Vaulted primary suite with private deck",
      "Heated-floor primary bath",
      "Walk-in closet",
      "Smart home system",
      "Security system",
      "Finished basement (multiuse)",
      "Fully renovated to studs (2004)",
      "Poured concrete foundation",
      "Natural gas + electric",
      "2 stories + basement",
    ],
    schools: [
      { name: "Sacajawea Elementary", level: "Elementary", distance: "0.2 mi" },
      { name: "Jane Addams Middle", level: "Middle", distance: "1.1 mi" },
      { name: "Nathan Hale High", level: "High", distance: "0.9 mi" },
    ],
  },
  // Add more houses here
];
