const HOUSES = [
  {
    id: "1905-ne-125th",
    color: "#E8735A",
    nickname: "Pinehurst",
    address: "1905 NE 125th St, Seattle, WA 98125",
    image: "images/1905-ne-125th.jpg",
    url: "https://www.compass.com/homedetails/1905-NE-125th-St-Seattle-WA-98125/1RJPQJ_pid/",
    status: "Active",
    daysOnMarket: 10,
    price: 1068000,
    lastSoldPrice: 530000,
    lastSoldYear: 2014,
    sqft: 1930,
    lotSqft: 7214,
    bedrooms: 3,
    bathrooms: 3,
    bathroomsFull: 2,
    bathroomsThreeQuarter: 0,
    bathroomsHalf: 1,
    yearBuilt: 2005,
    yearRenovated: null,
    stories: 2,
    basement: false,
    basementSqft: 0,
    parking: "2 covered (detached garage)",
    annualTax: 11322,
    hoaMonthly: 0,
    heating: "Forced air",
    cooling: "None",
    neighborhood: "Pinehurst (Victory Heights)",
    features: [
      "Move-in ready Craftsman",
      "New roof",
      "New interior paint",
      "New flooring",
      "Granite countertops",
      "Stainless steel appliances",
      "Gas fireplace",
      "Hardwood floors",
      "Flagstone patio",
      "Fully fenced backyard",
      "Poured concrete foundation",
      "Natural gas + electric",
    ],
    schools: [
      { name: "Sacajawea Elementary", level: "Elementary", distance: "1.4 mi" },
      { name: "Jane Addams Middle", level: "Middle", distance: "1.0 mi" },
      { name: "Nathan Hale High", level: "High", distance: "1.0 mi" },
    ],
  },
  {
    id: "2007-ne-137th",
    color: "#5BAD72",
    nickname: "Olympic Hills",
    address: "2007 NE 137th St, Seattle, WA 98125",
    image: "images/2007-ne-137th.jpg",
    url: "https://www.compass.com/homedetails/2007-NE-137th-St-Seattle-WA-98125/1S7VFL_pid/",
    status: "Active",
    daysOnMarket: 10,
    price: 950000,
    lastSoldPrice: 600000,
    lastSoldYear: 2022,
    sqft: 1760,
    lotSqft: 5000,
    bedrooms: 3,
    bathrooms: 2,
    bathroomsFull: 1,
    bathroomsThreeQuarter: 1,
    bathroomsHalf: 0,
    yearBuilt: 1952,
    yearRenovated: 2024,
    stories: 1,
    basement: false,
    basementSqft: 0,
    parking: "1 covered (attached garage) + driveway",
    annualTax: 6944,
    hoaMonthly: 0,
    heating: "Heat pump + forced air furnace",
    cooling: "Heat pump",
    neighborhood: "Pinehurst / Olympic Hills",
    features: [
      "Extensively reimagined rambler (turnkey)",
      "6-burner gas range + double ovens (LG Café)",
      "Quartz counters, custom cabinetry",
      "Dual-zone wine cooler",
      "Hand-painted Spanish tile",
      "Master walk-in closet w/ laundry",
      "Jetted tub in master bath",
      "Swim spa + entertaining patio",
      "Fully fenced yard, mature landscaping",
      "Skylit workshop",
      "New 200-amp panel, sewer, PEX, windows, siding",
      "RV/EV-ready, metal roof",
    ],
    schools: [
      { name: "Olympic Hills Elementary", level: "Elementary", distance: "0.3 mi" },
      { name: "Jane Addams Middle", level: "Middle", distance: "1.4 mi" },
      { name: "Nathan Hale High", level: "High", distance: "1.5 mi" },
    ],
  },
  {
    id: "13721-meridian",
    color: "#9B6BB5",
    nickname: "Haller Lake",
    address: "13721 Meridian Ave N, Seattle, WA 98133",
    image: "images/13721-meridian.jpg",
    url: "https://www.compass.com/homedetails/13721-Meridian-Ave-N-Seattle-WA-98133/1RPIO7_pid/",
    status: "Active",
    daysOnMarket: 26,
    price: 1125000,
    lastSoldPrice: 599950,
    lastSoldYear: 2014,
    sqft: 2167,
    lotSqft: 3995,
    bedrooms: 3,
    bathrooms: 3,
    bathroomsFull: 2,
    bathroomsThreeQuarter: 0,
    bathroomsHalf: 1,
    yearBuilt: 2014,
    yearRenovated: null,
    stories: 2,
    basement: false,
    basementSqft: 0,
    parking: "2 attached garage + driveway (EV-ready)",
    annualTax: 10779,
    hoaMonthly: 85,
    heating: "Ductless + HRV/ERV",
    cooling: "Ductless A/C",
    neighborhood: "Haller Lake",
    features: [
      "Move-in ready, Built Green 3-Star",
      "European-style custom cabinetry",
      "Quartz counters",
      "Stainless steel appliances (energy efficient)",
      "Open floor plan / great room",
      "Master suite w/ spa bath + walk-in closet",
      "Upper-level laundry room",
      "Bonus room (2nd floor)",
      "Private fenced yard, artificial low-maint lawn",
      "Gas fireplace, engineered hardwood",
      "Corner lot, territorial views, EV-ready",
      "Adjacent HOA park, near Light Rail",
    ],
    schools: [
      { name: "James Baldwin Elementary", level: "Elementary", distance: "1.0 mi" },
      { name: "Robert Eagle Staff Middle", level: "Middle", distance: "2.4 mi" },
      { name: "Ingraham High", level: "High", distance: "0.3 mi" },
    ],
  },
  // Add more houses here
];
